#!/bin/bash

apm install advanced-open-file
apm install autocomplete-modules
apm install color-picker
apm install custom-title
apm install file-icons
apm install flex-tool-bar
apm install git-blame
apm install highlight-selected
apm install language-applescript
apm install language-babel
apm install language-docker
apm install language-jade
apm install language-nginx
apm install language-pug
apm install language-slim
apm install linter
apm install linter-docker
apm install linter-eslint
apm install linter-scss-lint
apm install linter-stylelint
apm install maximize-panes
apm install merge-conflicts
apm install nice-index
apm install nucleus-dark-ui
apm install nuclide
apm install pretty-json
apm install set-syntax
apm install todo-show
apm install tool-bar
apm install vim-mode-plus
apm install zentabs
