#!/usr/bin/env osascript -l JavaScript

function run() {
  AtomMinima.run("~/Dev/System/atom/atom-minima", {
    root: "atom atom-minima minima-ui minima-syntax --dev",
    ui: "cd minima-ui",
    syntax: "cd minima-syntax",
  });
}

const iTerm = Application("iTerm");
const Utils = Library("utils");

iTerm.includeStandardAdditions = true;
iTerm.activate();

const AtomMinima = {
  run(path, cmd) {
    const container = iTerm.createWindowWithDefaultProfile();

    const rootSession = container.currentSession;
    const uiSession = rootSession.splitHorizontallyWithDefaultProfile();
    const syntaxSession = uiSession.splitVerticallyWithDefaultProfile();

    Utils.prepareSessions(path, [rootSession, uiSession, syntaxSession]);

    rootSession.write({ text: cmd.root, newline: false });
    uiSession.write({ text: cmd.ui });
    syntaxSession.write({ text: cmd.syntax });
    rootSession.select();
  }
};
