#!/usr/bin/env osascript -l JavaScript

function run() {
  Blog.run('~/Dev/Projects/alexfedoseev.com', {
    root: 'git status',
    bsb: 'yarn run bsb:clean:watch',
    css: 'yarn run css:watch',
    server: 'yarn run webpack:server',
  });
}

const iTerm = Application('iTerm');
const Utils = Library('utils');

iTerm.includeStandardAdditions = true;
iTerm.activate();

const Blog = {
  run(path, cmd) {
    const container = iTerm.createWindowWithDefaultProfile();

    const rootSession = container.currentSession;
    const bsbSession = rootSession.splitHorizontallyWithDefaultProfile();
    const cssSession = bsbSession.splitVerticallyWithDefaultProfile();
    const serverSession = cssSession.splitVerticallyWithDefaultProfile();

    Utils.prepareSessions(path, [rootSession, bsbSession, cssSession, serverSession]);

    rootSession.write({ text: cmd.root });
    bsbSession.write({ text: cmd.bsb, newline: false });
    cssSession.write({ text: cmd.css, newline: false });
    serverSession.write({ text: cmd.server, newline: false });
    bsbSession.select();
  },
};
