#!/usr/bin/env osascript -l JavaScript

function run() {
  Blog.run('~/Dev/Projects/alexfedoseev.com/blog', {
    root: 'git status',
    server: 'yarn start',
  });
}

const iTerm = Application('iTerm');
const Utils = Library('utils');

iTerm.includeStandardAdditions = true;
iTerm.activate();

const Blog = {
  run(path, cmd) {
    const container = iTerm.createWindowWithDefaultProfile();

    const rootSession = container.currentSession;
    const serverSession = rootSession.splitHorizontallyWithDefaultProfile();

    Utils.prepareSessions(path, [rootSession, serverSession]);

    rootSession.write({ text: cmd.root });
    serverSession.write({ text: cmd.server, newline: false });
    serverSession.select();
  },
};
