#!/usr/bin/env osascript -l JavaScript

function run() {
  Conform.run('~/Dev/Libs/conform', {
    root: 'atom conform conform-derive examples .',
    tests: 'cargo test',
  });
}

const iTerm = Application('iTerm');
const Utils = Library('utils');

iTerm.includeStandardAdditions = true;
iTerm.activate();

const Conform = {
  run(path, cmd) {
    const container = iTerm.createWindowWithDefaultProfile();

    const rootSession = container.currentSession;
    const testsSession = rootSession.splitHorizontallyWithDefaultProfile();

    Utils.prepareSessions(path, [rootSession, testsSession]);

    rootSession.write({ text: cmd.root, newline: false });
    testsSession.write({ text: cmd.tests, newline: false });
    rootSession.select();
  },
};
