#!/usr/bin/env osascript -l JavaScript

function run() {
  Dotfiles.run('~/Dev/System/dotfiles', {
    editor: 'atom .',
    cli: 'git status',
  });
}

const iTerm = Application('iTerm');
const Utils = Library('utils');

iTerm.includeStandardAdditions = true;
iTerm.activate();

const Dotfiles = {
  run(path, cmd) {
    const container = iTerm.createWindowWithDefaultProfile();

    const editorSession = container.currentSession;
    const cliSession = editorSession.splitHorizontallyWithDefaultProfile();

    Utils.prepareSessions(path, [editorSession, cliSession]);

    editorSession.write({ text: cmd.editor, newline: false });
    cliSession.write({ text: cmd.cli });
  },
};
