#!/usr/bin/env osascript -l JavaScript

function run() {
  Everwise.run('~/Dev/Projects/shakacode.com/consulting/everwise/tasmania', {
    client: 'cd spas',
    api: 'git status',
    clientServer: 'cd spas && yarn start',
    apiServer: 'foreman start -f Procfile.dev',
  });
}

const iTerm = Application('iTerm');
const Utils = Library('utils');

iTerm.includeStandardAdditions = true;
iTerm.activate();

const Everwise = {
  run(path, cmd) {
    const container = iTerm.createWindowWithDefaultProfile();

    const clientSession = container.currentSession;
    const clientServerSession = clientSession.splitHorizontallyWithDefaultProfile();
    const apiSession = clientSession.splitVerticallyWithDefaultProfile();
    const apiServerSession = clientServerSession.splitVerticallyWithDefaultProfile();

    Utils.prepareSessions(path, [
      clientSession,
      apiSession,
      clientServerSession,
      apiServerSession,
    ]);

    clientSession.write({ text: cmd.client });
    apiSession.write({ text: cmd.api });
    clientServerSession.write({ text: cmd.clientServer, newline: false });
    apiServerSession.write({ text: cmd.apiServer, newline: false });
  },
};
