#!/usr/bin/env osascript -l JavaScript

function run() {
  const Shaka = Library('shaka');

  Shaka.run('~/Dev/Projects/shakacode.com/friendsandguests', {
    root: 'git status',
    client: 'cd client',
    server: 'script/docker/run:dev',
  });
}
