#!/usr/bin/env osascript -l JavaScript

function run() {
  const Shaka = Library('shaka');

  Shaka.run('~/Dev/Projects/shakacode.com/fng', {
    root: 'cd friendsandguests && git status',
    client: 'cd friendsandguests/client',
    server: 'scripts/start',
  });
}
