#!/usr/bin/env osascript -l JavaScript

function run() {
  const Lib = Library('lib-js');

  Lib.run('~/Dev/Libs/react-validation-layer', {
    root: 'git status',
    build: 'yarn start',
    server: 'cd website',
  });
}
