#!/usr/bin/env osascript -l JavaScript

function run() {
  const Shaka = Library('shaka');

  Shaka.run('~/Dev/Projects/shakacode.com/vrbestprice', {
    root: 'atom client .',
    client: 'cd client && git status',
    server: 'docker-compose up',
  });
}
