-- Core
require("editor.app").keymaps()
require("editor.editing").keymaps()
require("editor.navigation").keymaps()
require("editor.buffers").keymaps()
require("editor.windows").keymaps()
require("editor.terminal").keymaps()

-- Plugins
require("plugins.lazy").keymaps()
require("plugins.pounce").keymaps()
require("plugins.comment").keymaps()
require("plugins.telescope").keymaps()
require("plugins.treesitter").keymaps()
require("plugins.zen-mode").keymaps()
require("plugins.spectre").keymaps()
require("plugins.lualine").keymaps()
require("plugins.neo-tree").keymaps()
require("plugins.persistence").keymaps()
require("plugins.toggleterm").keymaps()
require("plugins.lsp.mason").keymaps()
require("plugins.lsp.lspsaga").keymaps()
require("plugins.lsp.lsp-lines").keymaps()
require("plugins.git.lazygit").keymaps()
require("plugins.git.gitsigns").keymaps()
require("plugins.git.diffview").keymaps()
