export NPM_CONFIG_PREFIX="$HOME/.npm-global"

alias n="npm "
alias ns="npm start"
alias nt="npm test"
alias nr="npm run "
alias ni="npm install --save-exact "
alias nid="npm install --save-dev --save-exact "
alias nrm="npm remove --save "
alias nrmd="npm remove --save-dev "
alias no="npm outdated"
alias nup="ncu --upgrade --interactive --format group"
alias nupw="ncu --workspaces --upgrade --interactive --format group"
alias nlg="npm ls -g --depth=0"
alias nfuck="rm -rf node_modules && npm cache clean && npm install"

alias y="yarn "
alias ys="yarn start "
alias yt="yarn test"
alias yr="yarn run "
alias yi="yarn add --exact "
alias yid="yarn add --dev --exact "
alias yrm="yarn remove "
alias yo="yarn outdated"
alias yup="yarn upgrade-interactive --exact --latest"
alias yar="rm -rf node_modules && yarn"
alias yarr="rm -rf node_modules && yarn cache clean && yarn"
